application: taburlrasa
version: 1
runtime: python27
api_version: 1
threadsafe: yes
module: default

handlers:
- url: .*
  script: main.app
- url: /.*
  script: templates.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
